In [2]:
# 1. 라이브러리 및 경로 설정

from pathlib import Path
import time
import random
import pandas as pd

from google_play_scraper import app, reviews, Sort

try:
    from google_play_scraper import search
    SEARCH_AVAILABLE = True
except ImportError:
    SEARCH_AVAILABLE = False

PROJECT_DIR = Path(r"C:\취준\mobile-game-retention-review-ua-analysis")

RAW_DIR = PROJECT_DIR / "data" / "raw"
COLLECTED_DIR = PROJECT_DIR / "data" / "collected"
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"
OUTPUT_TABLE_DIR = PROJECT_DIR / "outputs" / "tables"
OUTPUT_FIGURE_DIR = PROJECT_DIR / "outputs" / "figures"
DOCS_DIR = PROJECT_DIR / "docs"
NOTEBOOK_DIR = PROJECT_DIR / "notebooks"

for path in [
    RAW_DIR,
    COLLECTED_DIR,
    PROCESSED_DIR,
    OUTPUT_TABLE_DIR,
    OUTPUT_FIGURE_DIR,
    DOCS_DIR,
    NOTEBOOK_DIR,
]:
    path.mkdir(parents=True, exist_ok=True)

print("Project directory:", PROJECT_DIR)
print("Collected directory:", COLLECTED_DIR)
print("Search available:", SEARCH_AVAILABLE)

Project directory: C:\취준\mobile-game-retention-review-ua-analysis
Collected directory: C:\취준\mobile-game-retention-review-ua-analysis\data\collected
Search available: True

In [3]:
# 2. 수집 설정

LANG = "en"
COUNTRY = "us"

TARGET_APP_COUNT = 100
REVIEWS_PER_APP = 100
REVIEW_SORT = Sort.NEWEST

print("Target apps:", TARGET_APP_COUNT)
print("Reviews per app:", REVIEWS_PER_APP)

Target apps: 100
Reviews per app: 100

In [4]:
# 3. 검색 기반 앱 ID 수집 + 수동 보완

manual_app_ids = [
    "com.king.candycrushsaga",
    "com.supercell.clashofclans",
    "com.supercell.clashroyale",
    "com.supercell.brawlstars",
    "com.roblox.client",
    "com.nianticlabs.pokemongo",
    "com.vizorapps.klondike",
    "com.playrix.gardenscapes",
    "com.playrix.homescapes",
    "com.playrix.fishdomdd.gplay",
    "com.outfit7.mytalkingtomfree",
    "com.outfit7.mytalkingtom2",
    "com.outfit7.mytalkingangela2",
    "com.miniclip.eightballpool",
    "com.easybrain.sudoku.android",
    "com.peoplefun.wordcross",
    "com.tripledot.solitaire",
    "com.tripledot.woodoku",
    "com.halfbrick.fruitninjafree",
    "com.halfbrick.jetpackjoyride",
    "com.kiloo.subwaysurf",
    "com.imangi.templerun2",
    "com.rovio.baba",
    "com.rovio.angrybirds2",
    "com.innersloth.spacemafia",
    "com.bigduckgames.flow",
    "com.scopely.monopolygo",
    "com.ludo.king",
    "com.ea.game.pvzfree_row",
    "com.zynga.words3",
    "com.zynga.farmville3",
    "com.activision.callofduty.shooter",
    "com.tencent.ig",
    "com.mobile.legends",
    "jp.pokemon.pokemonunite",
]

search_queries = [
    "casual games",
    "hyper casual games",
    "arcade games",
    "puzzle games",
    "runner games",
    "idle games",
    "io games",
    "merge games",
    "simulation games",
    "mobile games",
]

app_ids = []

if SEARCH_AVAILABLE:
    for query in search_queries:
        try:
            results = search(
                query,
                lang=LANG,
                country=COUNTRY,
                n_hits=30
            )

            for item in results:
                app_id = item.get("appId")
                if app_id and app_id not in app_ids:
                    app_ids.append(app_id)

            print(f"Query '{query}' collected. Current app count: {len(app_ids)}")
            time.sleep(random.uniform(0.5, 1.0))

        except Exception as e:
            print(f"Search failed for query '{query}': {e}")

for app_id in manual_app_ids:
    if app_id not in app_ids:
        app_ids.append(app_id)

app_ids = app_ids[:TARGET_APP_COUNT]

print("Final app ids:", len(app_ids))
print(app_ids[:20])

Query 'casual games' collected. Current app count: 24
Query 'hyper casual games' collected. Current app count: 42
Query 'arcade games' collected. Current app count: 62
Query 'puzzle games' collected. Current app count: 80
Query 'runner games' collected. Current app count: 97
Query 'idle games' collected. Current app count: 127
Query 'io games' collected. Current app count: 153
Query 'merge games' collected. Current app count: 183
Query 'simulation games' collected. Current app count: 209
Query 'mobile games' collected. Current app count: 228
Final app ids: 100
['com.king.candycrushsaga', 'com.moonactive.coinmaster', 'com.JindoBlu.OfflineGames', 'com.king.candycrushsodasaga', 'com.block.juggle', 'com.playrix.fishdomdd.gplay', 'com.roblox.client', 'com.dreamgames.royalmatch', 'com.miniclip.carrom', 'com.merge.match3mystery', 'com.farlightgames.pgame.gp', 'com.superking.parchisi.star', 'com.miniclip.eightballpool', 'com.wildspike.wormszone', 'find.out.hidden.objects.seek.puzzle.games.free', 'com.rubygames.assassin', 'com.king.candycrushjellysaga', 'com.king.candycrush4', 'com.king.bubblewitch3', 'com.vitastudio.mahjong']

In [5]:
# 4. 앱 메타데이터 수집
def safe_get_app_info(app_id, lang="en", country="us"):
    try:
        info = app(app_id, lang=lang, country=country)
        return {
            "app_id": app_id,
            "title": info.get("title"),
            "developer": info.get("developer"),
            "genre": info.get("genre"),
            "genre_id": info.get("genreId"),
            "score": info.get("score"),
            "ratings_count": info.get("ratings"),
            "reviews_count": info.get("reviews"),
            "installs": info.get("installs"),
            "min_installs": info.get("minInstalls"),
            "real_installs": info.get("realInstalls"),
            "free": info.get("free"),
            "price": info.get("price"),
            "currency": info.get("currency"),
            "contains_ads": info.get("containsAds"),
            "in_app_purchase": info.get("offersIAP"),
            "updated": info.get("updated"),
            "released": info.get("released"),
            "content_rating": info.get("contentRating"),
            "url": info.get("url"),
        }
    except Exception as e:
        return {
            "app_id": app_id,
            "error": str(e),
        }


app_info_rows = []

for i, app_id in enumerate(app_ids, start=1):
    row = safe_get_app_info(app_id, lang=LANG, country=COUNTRY)
    app_info_rows.append(row)

    print(f"[{i}/{len(app_ids)}] {app_id} - {row.get('title')}")
    time.sleep(random.uniform(0.3, 0.8))

apps_df = pd.DataFrame(app_info_rows)

display(apps_df.head())
print("Shape:", apps_df.shape)
print("Error count:", apps_df["error"].notna().sum() if "error" in apps_df.columns else 0)

apps_df.to_csv(
    COLLECTED_DIR / "google_play_apps.csv",
    index=False,
    encoding="utf-8-sig",
)

print("Saved:", COLLECTED_DIR / "google_play_apps.csv")

[1/100] com.king.candycrushsaga - Candy Crush Saga
[2/100] com.moonactive.coinmaster - Coin Master
[3/100] com.JindoBlu.OfflineGames - Offline Games - No Wifi Games
[4/100] com.king.candycrushsodasaga - Candy Crush Soda Saga
[5/100] com.block.juggle - Block Blast!
[6/100] com.playrix.fishdomdd.gplay - Fishdom
[7/100] com.roblox.client - Roblox
[8/100] com.dreamgames.royalmatch - Royal Match
[9/100] com.miniclip.carrom - Carrom Pool: Disc Game
[10/100] com.merge.match3mystery - Mistfall Match: Design & Blast
[11/100] com.farlightgames.pgame.gp - Clash of Critters
[12/100] com.superking.parchisi.star - Parchisi STAR Online
[13/100] com.miniclip.eightballpool - 8 Ball Pool
[14/100] com.wildspike.wormszone - Worms Zone .io - Hungry Snake
[15/100] find.out.hidden.objects.seek.puzzle.games.free - Find It Out® - Hidden Object
[16/100] com.rubygames.assassin - Hunter Assassin
[17/100] com.king.candycrushjellysaga - Candy Crush Jelly Saga
[18/100] com.king.candycrush4 - Candy Crush Friends Saga
[19/100] com.king.bubblewitch3 - Bubble Witch 3 Saga
[20/100] com.vitastudio.mahjong - Vita Mahjong
[21/100] com.yodo1.crossyroad - Crossy Road
[22/100] com.firsttouchgames.dls7 - Dream League Soccer 2026
[23/100] com.vincentb.MobControl - Mob Control
[24/100] com.playrix.township - Township
[25/100] com.mediocre.smashhit - Smash Hit
[26/100] io.voodoo.holeio - Hole.io
[27/100] com.superbox.aos.collecthole - Drop in the Hole
[28/100] com.kitkagames.fallbuddies - Stumble Guys
[29/100] com.JindoBlu.Antistress - Antistress - relaxation toys
[30/100] com.playrix.homescapes - Homescapes
[31/100] com.rovio.baba - Angry Birds 2
[32/100] com.mojang.minecraftpe - Minecraft: Dream it, Build it!
[33/100] bubbleshooter.orig - Bubble Shooter - Classic Pop
[34/100] com.WalkTalk.FlightMaster - Epic Plane Evolution
[35/100] com.dreamgames.royalkingdom - Royal Kingdom
[36/100] net.peakgames.toonblast - Toon Blast
[37/100] com.zeptolab.ctr.ads - Cut the Rope
[38/100] com.spinmaster.gabbysdollhouse - Gabbys Dollhouse: Games & Cats
[39/100] io.voodoo.paper2 - Paper.io 2
[40/100] com.sega.sonicdash - Sonic Dash Run
[41/100] com.robtopx.geometryjumplite - Geometry Dash Lite
[42/100] net.peakgames.match - Match Factory!
[43/100] com.os.space.force.galaxy.alien - Galaxiga: Galaxy Arcade Game
[44/100] eu.bandainamcoent.pacman256 - PAC-MAN 256 - Endless Maze
[45/100] com.nintendo.zara - Super Mario Run
[46/100] com.ea.game.pvzfree_row - Plants vs. Zombies™
[47/100] com.kiloo.subwaysurf - Subway Surfers
[48/100] com.halfbrick.fruitninjafree - Fruit Ninja®
[49/100] com.fingersoft.hcr2 - Hill Climb Racing 2
[50/100] com.greencod.pinballdeluxereloaded - Pinball Deluxe: Reloaded
[51/100] com.imangi.templerun2 - Temple Run 2: Endless Escape
[52/100] com.youmusic.magictiles - Magic Tiles 3™ - Piano Game
[53/100] com.playgendary.sportmasters - Bouncemasters: Penguin Games
[54/100] com.fgol.HungrySharkEvolution - Hungry Shark Evolution
[55/100] com.ea.game.nfs14_row - Need for Speed™ No Limits
[56/100] com.gameloft.android.ANMP.GloftA8HM - Asphalt 8 - Car Racing Game
[57/100] com.gameloft.android.ANMP.GloftDMHM - Minion Rush: Running Game
[58/100] com.outfit7.talkingtomgoldrun - Talking Tom Gold Run
[59/100] com.imangi.templerun - Temple Run
[60/100] com.sybogames.subway.surfers.game - Subway Surfers City
[61/100] com.nekki.shadowfight3 - Shadow Fight 3 - RPG fighting
[62/100] com.outfit7.herodash - Talking Tom: Hero Dash Run
[63/100] com.easybrain.jigsaw.puzzles - Jigsaw Puzzles - Puzzle Games
[64/100] com.bandagames.mpuzzle.gp - Magic Jigsaw Puzzles－Games HD
[65/100] com.easybrain.block.puzzle.games - Blockudoku®: Block Puzzle Game
[66/100] com.gamovation.tileclub - Tile Club - Match Puzzle Games
[67/100] com.easybrain.sudoku.android - Sudoku.com - Classic Sudoku
[68/100] com.inspiredsquare.jupiter - 2248 - Numbers Game 2048
[69/100] where.my.seat.taken.logic.puzzle.brain.mind - Where's My Seat?・Logic Puzzles
[70/100] com.zynga.pottermatch - Harry Potter: Puzzles & Spells
[71/100] com.easybrain.art.puzzle - Art Puzzle - Puzzle Games
[72/100] com.uken.mattel.match - Mattel Match
[73/100] com.weplaydots.twodotsandroid - Two Dots: Brain Puzzle Games
[74/100] com.playrix.gardenscapes - Gardenscapes
[75/100] com.tripledot.triple.tile.match.pair.game.three.master.object - Triple Tile: Match Puzzle Game
[76/100] com.rvappstudios.jigsaw.puzzles.kids - Puzzle Kids: Jigsaw Puzzles
[77/100] com.ecffri.arrows - Arrows – Puzzle Escape
[78/100] com.oakever.tiletrip - Tile Explorer - Triple Match
[79/100] com.smallgiantgames.empires - Empires & Puzzles: Match-3 RPG
[80/100] com.Seriously.BestFiends - Best Fiends - Match 3 Puzzles
[81/100] com.gameloft.android.ANMP.GloftICHM - Sonic Runners Adventure game
[82/100] com.devsisters.cos - CookieRun: OvenSmash
[83/100] com.halfbrick.aeroracer - Jetpack Joyride Racing
[84/100] com.solou.catendless.run - Cat Runner: Decorate Home
[85/100] com.sega.sonicboomandroid - Sonic Boom Dash
[86/100] com.rioo.runnersubway - Subway Princess Runner
[87/100] com.sega.sprint - Sonic Forces: PvP Race
[88/100] com.robtopx.geometryjump - Geometry Dash
[89/100] com.pocketchamps.game - Pocket Champs: 3D Racing Games
[90/100] com.nekki.vector - Vector
[91/100] com.creations.runnergame - Kooply Run™: Play and Create!
[92/100] com.vectorunit.cobalt.googleplay - Beach Buggy Racing 2
[93/100] com.playgendary.tom - Tomb of the Mask: Old Maze
[94/100] com.streetrush.runninggame - Street Rush - Running Game
[95/100] com.crazylabs.lady.bug - Miraculous Ladybug & Cat Noir
[96/100] com.robtopx.geometrydashsubzero - Geometry Dash SubZero
[97/100] com.vectorunit.purple.googleplay - Beach Buggy Racing
[98/100] com.OctocubeGamesCompany.CIFI - Cell: Idle Factory Incremental
[99/100] com.fluffyfairygames.idleminertycoon - Idle Miner Tycoon: Gold Games
[100/100] com.codigames.hotel.empire.tycoon.idle.game - Hotel Empire Tycoon－Idle Game

,app_id,title,developer,genre,genre_id,score,ratings_count,reviews_count,installs,min_installs,real_installs,free,price,currency,contains_ads,in_app_purchase,updated,released,content_rating,url
0,com.king.candycrushsaga,Candy Crush Saga,King,Casual,GAME_CASUAL,4.626835,38939374.0,2094860.0,"1,000,000,000+",1000000000,2261402010,True,0.0,USD,True,True,1.779963e+09,"Nov 15, 2012",Everyone,https://play.google.com/store/apps/details?id=...
1,com.moonactive.coinmaster,Coin Master,Moon Active,Casual,GAME_CASUAL,4.751316,10382177.0,691073.0,"100,000,000+",100000000,345137646,True,0.0,USD,True,True,1.780298e+09,"Feb 4, 2016",Teen,https://play.google.com/store/apps/details?id=...
2,com.JindoBlu.OfflineGames,Offline Games - No Wifi Games,JindoBlu,Casual,GAME_CASUAL,4.640068,457166.0,13820.0,"100,000,000+",100000000,192362829,True,0.0,USD,True,True,1.780866e+09,"Aug 4, 2023",Everyone,https://play.google.com/store/apps/details?id=...
3,com.king.candycrushsodasaga,Candy Crush Soda Saga,King,Casual,GAME_CASUAL,4.578125,8874939.0,390688.0,"500,000,000+",500000000,616471412,True,0.0,USD,True,True,1.779468e+09,"Nov 11, 2014",Everyone,https://play.google.com/store/apps/details?id=...
4,com.block.juggle,Block Blast!,HungryStudio,Puzzle,GAME_PUZZLE,4.820772,4769045.0,70652.0,"500,000,000+",500000000,969039804,True,0.0,USD,True,True,1.780662e+09,"Sep 23, 2022",Everyone,https://play.google.com/store/apps/details?id=...

Shape: (100, 20)
Error count: 0
Saved: C:\취준\mobile-game-retention-review-ua-analysis\data\collected\google_play_apps.csv

In [6]:
# 5. 수집 가능한 앱만 필터링
valid_apps_df = apps_df[
    apps_df["title"].notna()
].copy()

# 게임 장르만 최대한 유지
valid_apps_df = valid_apps_df[
    valid_apps_df["genre"].fillna("").str.contains("Game|Action|Arcade|Casual|Puzzle|Simulation|Strategy|Role Playing|Racing|Sports", case=False, regex=True)
    | valid_apps_df["genre_id"].fillna("").str.contains("GAME", case=False, regex=True)
].copy()

valid_app_ids = valid_apps_df["app_id"].dropna().unique().tolist()

print("Valid apps:", len(valid_app_ids))
display(valid_apps_df[["app_id", "title", "genre", "score", "installs", "contains_ads", "in_app_purchase"]].head(20))

valid_apps_df.to_csv(
    COLLECTED_DIR / "google_play_apps_valid.csv",
    index=False,
    encoding="utf-8-sig",
)

Valid apps: 100

,app_id,title,genre,score,installs,contains_ads,in_app_purchase
0,com.king.candycrushsaga,Candy Crush Saga,Casual,4.626835,"1,000,000,000+",True,True
1,com.moonactive.coinmaster,Coin Master,Casual,4.751316,"100,000,000+",True,True
2,com.JindoBlu.OfflineGames,Offline Games - No Wifi Games,Casual,4.640068,"100,000,000+",True,True
3,com.king.candycrushsodasaga,Candy Crush Soda Saga,Casual,4.578125,"500,000,000+",True,True
4,com.block.juggle,Block Blast!,Puzzle,4.820772,"500,000,000+",True,True
5,com.playrix.fishdomdd.gplay,Fishdom,Puzzle,4.604287,"100,000,000+",False,True
6,com.roblox.client,Roblox,Adventure,4.185744,"1,000,000,000+",False,True
7,com.dreamgames.royalmatch,Royal Match,Puzzle,4.635291,"100,000,000+",False,True
8,com.miniclip.carrom,Carrom Pool: Disc Game,Sports,4.483208,"500,000,000+",True,True
9,com.merge.match3mystery,Mistfall Match: Design & Blast,Casual,4.821782,"500,000+",True,True
10,com.farlightgames.pgame.gp,Clash of Critters,Casual,4.515411,"1,000,000+",False,True
11,com.superking.parchisi.star,Parchisi STAR Online,Board,4.682722,"100,000,000+",True,True
12,com.miniclip.eightballpool,8 Ball Pool,Sports,4.795916,"1,000,000,000+",True,True
13,com.wildspike.wormszone,Worms Zone .io - Hungry Snake,Action,4.278161,"500,000,000+",True,True
14,find.out.hidden.objects.seek.puzzle.games.free,Find It Out® - Hidden Object,Puzzle,4.855531,"10,000,000+",True,True
15,com.rubygames.assassin,Hunter Assassin,Action,4.217198,"500,000,000+",True,True
16,com.king.candycrushjellysaga,Candy Crush Jelly Saga,Puzzle,4.634216,"100,000,000+",True,True
17,com.king.candycrush4,Candy Crush Friends Saga,Casual,4.675050,"50,000,000+",True,True
18,com.king.bubblewitch3,Bubble Witch 3 Saga,Puzzle,4.658231,"100,000,000+",True,True
19,com.vitastudio.mahjong,Vita Mahjong,Board,4.782185,"100,000,000+",True,True

In [7]:
# 6. 리뷰 수집 함수
def safe_collect_reviews(app_id, app_title=None, count=100, lang="en", country="us"):
    """
    앱별 최신 리뷰를 수집한다.
    실패 시 빈 리스트 반환.
    """
    try:
        result, continuation_token = reviews(
            app_id,
            lang=lang,
            country=country,
            sort=REVIEW_SORT,
            count=count,
        )

        rows = []
        for r in result:
            rows.append({
                "app_id": app_id,
                "title": app_title,
                "review_id": r.get("reviewId"),
                "review_text": r.get("content"),
                "review_score": r.get("score"),
                "review_date": r.get("at"),
                "thumbs_up_count": r.get("thumbsUpCount"),
                "review_created_version": r.get("reviewCreatedVersion"),
            })

        return rows

    except Exception as e:
        print(f"Review collection failed: {app_id} / {e}")
        return []

In [8]:
# 7. 앱별 리뷰 수집
all_review_rows = []

app_title_map = dict(zip(valid_apps_df["app_id"], valid_apps_df["title"]))

for i, app_id in enumerate(valid_app_ids, start=1):
    title = app_title_map.get(app_id)

    rows = safe_collect_reviews(
        app_id=app_id,
        app_title=title,
        count=REVIEWS_PER_APP,
        lang=LANG,
        country=COUNTRY,
    )

    all_review_rows.extend(rows)

    print(f"[{i}/{len(valid_app_ids)}] {title} ({app_id}) - reviews: {len(rows)} / total: {len(all_review_rows)}")

    # 너무 빠른 요청 방지
    time.sleep(random.uniform(0.5, 1.2))

reviews_df = pd.DataFrame(all_review_rows)

display(reviews_df.head())
print("Review shape:", reviews_df.shape)
print("Unique apps in reviews:", reviews_df["app_id"].nunique() if len(reviews_df) > 0 else 0)

reviews_df.to_csv(
    COLLECTED_DIR / "google_play_reviews.csv",
    index=False,
    encoding="utf-8-sig",
)

print("Saved:", COLLECTED_DIR / "google_play_reviews.csv")

[1/100] Candy Crush Saga (com.king.candycrushsaga) - reviews: 100 / total: 100
[2/100] Coin Master (com.moonactive.coinmaster) - reviews: 100 / total: 200
[3/100] Offline Games - No Wifi Games (com.JindoBlu.OfflineGames) - reviews: 100 / total: 300
[4/100] Candy Crush Soda Saga (com.king.candycrushsodasaga) - reviews: 100 / total: 400
[5/100] Block Blast! (com.block.juggle) - reviews: 100 / total: 500
[6/100] Fishdom (com.playrix.fishdomdd.gplay) - reviews: 100 / total: 600
[7/100] Roblox (com.roblox.client) - reviews: 100 / total: 700
[8/100] Royal Match (com.dreamgames.royalmatch) - reviews: 100 / total: 800
[9/100] Carrom Pool: Disc Game (com.miniclip.carrom) - reviews: 100 / total: 900
[10/100] Mistfall Match: Design & Blast (com.merge.match3mystery) - reviews: 81 / total: 981
[11/100] Clash of Critters (com.farlightgames.pgame.gp) - reviews: 100 / total: 1081
[12/100] Parchisi STAR Online (com.superking.parchisi.star) - reviews: 100 / total: 1181
[13/100] 8 Ball Pool (com.miniclip.eightballpool) - reviews: 100 / total: 1281
[14/100] Worms Zone .io - Hungry Snake (com.wildspike.wormszone) - reviews: 100 / total: 1381
[15/100] Find It Out® - Hidden Object (find.out.hidden.objects.seek.puzzle.games.free) - reviews: 100 / total: 1481
[16/100] Hunter Assassin (com.rubygames.assassin) - reviews: 100 / total: 1581
[17/100] Candy Crush Jelly Saga (com.king.candycrushjellysaga) - reviews: 100 / total: 1681
[18/100] Candy Crush Friends Saga (com.king.candycrush4) - reviews: 100 / total: 1781
[19/100] Bubble Witch 3 Saga (com.king.bubblewitch3) - reviews: 100 / total: 1881
[20/100] Vita Mahjong (com.vitastudio.mahjong) - reviews: 100 / total: 1981
[21/100] Crossy Road (com.yodo1.crossyroad) - reviews: 100 / total: 2081
[22/100] Dream League Soccer 2026 (com.firsttouchgames.dls7) - reviews: 100 / total: 2181
[23/100] Mob Control (com.vincentb.MobControl) - reviews: 100 / total: 2281
[24/100] Township (com.playrix.township) - reviews: 100 / total: 2381
[25/100] Smash Hit (com.mediocre.smashhit) - reviews: 100 / total: 2481
[26/100] Hole.io (io.voodoo.holeio) - reviews: 100 / total: 2581
[27/100] Drop in the Hole (com.superbox.aos.collecthole) - reviews: 10 / total: 2591
[28/100] Stumble Guys (com.kitkagames.fallbuddies) - reviews: 100 / total: 2691
[29/100] Antistress - relaxation toys (com.JindoBlu.Antistress) - reviews: 100 / total: 2791
[30/100] Homescapes (com.playrix.homescapes) - reviews: 100 / total: 2891
[31/100] Angry Birds 2 (com.rovio.baba) - reviews: 100 / total: 2991
[32/100] Minecraft: Dream it, Build it! (com.mojang.minecraftpe) - reviews: 100 / total: 3091
[33/100] Bubble Shooter - Classic Pop (bubbleshooter.orig) - reviews: 100 / total: 3191
[34/100] Epic Plane Evolution (com.WalkTalk.FlightMaster) - reviews: 100 / total: 3291
[35/100] Royal Kingdom (com.dreamgames.royalkingdom) - reviews: 100 / total: 3391
[36/100] Toon Blast (net.peakgames.toonblast) - reviews: 100 / total: 3491
[37/100] Cut the Rope (com.zeptolab.ctr.ads) - reviews: 100 / total: 3591
[38/100] Gabbys Dollhouse: Games & Cats (com.spinmaster.gabbysdollhouse) - reviews: 100 / total: 3691
[39/100] Paper.io 2 (io.voodoo.paper2) - reviews: 100 / total: 3791
[40/100] Sonic Dash Run (com.sega.sonicdash) - reviews: 100 / total: 3891
[41/100] Geometry Dash Lite (com.robtopx.geometryjumplite) - reviews: 100 / total: 3991
[42/100] Match Factory! (net.peakgames.match) - reviews: 100 / total: 4091
[43/100] Galaxiga: Galaxy Arcade Game (com.os.space.force.galaxy.alien) - reviews: 100 / total: 4191
[44/100] PAC-MAN 256 - Endless Maze (eu.bandainamcoent.pacman256) - reviews: 100 / total: 4291
[45/100] Super Mario Run (com.nintendo.zara) - reviews: 100 / total: 4391
[46/100] Plants vs. Zombies™ (com.ea.game.pvzfree_row) - reviews: 100 / total: 4491
[47/100] Subway Surfers (com.kiloo.subwaysurf) - reviews: 100 / total: 4591
[48/100] Fruit Ninja® (com.halfbrick.fruitninjafree) - reviews: 100 / total: 4691
[49/100] Hill Climb Racing 2 (com.fingersoft.hcr2) - reviews: 100 / total: 4791
[50/100] Pinball Deluxe: Reloaded (com.greencod.pinballdeluxereloaded) - reviews: 100 / total: 4891
[51/100] Temple Run 2: Endless Escape (com.imangi.templerun2) - reviews: 100 / total: 4991
[52/100] Magic Tiles 3™ - Piano Game (com.youmusic.magictiles) - reviews: 100 / total: 5091
[53/100] Bouncemasters: Penguin Games (com.playgendary.sportmasters) - reviews: 100 / total: 5191
[54/100] Hungry Shark Evolution (com.fgol.HungrySharkEvolution) - reviews: 100 / total: 5291
[55/100] Need for Speed™ No Limits (com.ea.game.nfs14_row) - reviews: 100 / total: 5391
[56/100] Asphalt 8 - Car Racing Game (com.gameloft.android.ANMP.GloftA8HM) - reviews: 100 / total: 5491
[57/100] Minion Rush: Running Game (com.gameloft.android.ANMP.GloftDMHM) - reviews: 100 / total: 5591
[58/100] Talking Tom Gold Run (com.outfit7.talkingtomgoldrun) - reviews: 100 / total: 5691
[59/100] Temple Run (com.imangi.templerun) - reviews: 100 / total: 5791
[60/100] Subway Surfers City (com.sybogames.subway.surfers.game) - reviews: 100 / total: 5891
[61/100] Shadow Fight 3 - RPG fighting (com.nekki.shadowfight3) - reviews: 100 / total: 5991
[62/100] Talking Tom: Hero Dash Run (com.outfit7.herodash) - reviews: 100 / total: 6091
[63/100] Jigsaw Puzzles - Puzzle Games (com.easybrain.jigsaw.puzzles) - reviews: 100 / total: 6191
[64/100] Magic Jigsaw Puzzles－Games HD (com.bandagames.mpuzzle.gp) - reviews: 100 / total: 6291
[65/100] Blockudoku®: Block Puzzle Game (com.easybrain.block.puzzle.games) - reviews: 100 / total: 6391
[66/100] Tile Club - Match Puzzle Games (com.gamovation.tileclub) - reviews: 100 / total: 6491
[67/100] Sudoku.com - Classic Sudoku (com.easybrain.sudoku.android) - reviews: 100 / total: 6591
[68/100] 2248 - Numbers Game 2048 (com.inspiredsquare.jupiter) - reviews: 100 / total: 6691
[69/100] Where's My Seat?・Logic Puzzles (where.my.seat.taken.logic.puzzle.brain.mind) - reviews: 100 / total: 6791
[70/100] Harry Potter: Puzzles & Spells (com.zynga.pottermatch) - reviews: 100 / total: 6891
[71/100] Art Puzzle - Puzzle Games (com.easybrain.art.puzzle) - reviews: 100 / total: 6991
[72/100] Mattel Match (com.uken.mattel.match) - reviews: 97 / total: 7088
[73/100] Two Dots: Brain Puzzle Games (com.weplaydots.twodotsandroid) - reviews: 100 / total: 7188
[74/100] Gardenscapes (com.playrix.gardenscapes) - reviews: 100 / total: 7288
[75/100] Triple Tile: Match Puzzle Game (com.tripledot.triple.tile.match.pair.game.three.master.object) - reviews: 100 / total: 7388
[76/100] Puzzle Kids: Jigsaw Puzzles (com.rvappstudios.jigsaw.puzzles.kids) - reviews: 100 / total: 7488
[77/100] Arrows – Puzzle Escape (com.ecffri.arrows) - reviews: 100 / total: 7588
[78/100] Tile Explorer - Triple Match (com.oakever.tiletrip) - reviews: 100 / total: 7688
[79/100] Empires & Puzzles: Match-3 RPG (com.smallgiantgames.empires) - reviews: 100 / total: 7788
[80/100] Best Fiends - Match 3 Puzzles (com.Seriously.BestFiends) - reviews: 100 / total: 7888
[81/100] Sonic Runners Adventure game (com.gameloft.android.ANMP.GloftICHM) - reviews: 100 / total: 7988
[82/100] CookieRun: OvenSmash (com.devsisters.cos) - reviews: 100 / total: 8088
[83/100] Jetpack Joyride Racing (com.halfbrick.aeroracer) - reviews: 73 / total: 8161
[84/100] Cat Runner: Decorate Home (com.solou.catendless.run) - reviews: 100 / total: 8261
[85/100] Sonic Boom Dash (com.sega.sonicboomandroid) - reviews: 100 / total: 8361
[86/100] Subway Princess Runner (com.rioo.runnersubway) - reviews: 100 / total: 8461
[87/100] Sonic Forces: PvP Race (com.sega.sprint) - reviews: 100 / total: 8561
[88/100] Geometry Dash (com.robtopx.geometryjump) - reviews: 100 / total: 8661
[89/100] Pocket Champs: 3D Racing Games (com.pocketchamps.game) - reviews: 100 / total: 8761
[90/100] Vector (com.nekki.vector) - reviews: 100 / total: 8861
[91/100] Kooply Run™: Play and Create! (com.creations.runnergame) - reviews: 100 / total: 8961
[92/100] Beach Buggy Racing 2 (com.vectorunit.cobalt.googleplay) - reviews: 100 / total: 9061
[93/100] Tomb of the Mask: Old Maze (com.playgendary.tom) - reviews: 100 / total: 9161
[94/100] Street Rush - Running Game (com.streetrush.runninggame) - reviews: 100 / total: 9261
[95/100] Miraculous Ladybug & Cat Noir (com.crazylabs.lady.bug) - reviews: 100 / total: 9361
[96/100] Geometry Dash SubZero (com.robtopx.geometrydashsubzero) - reviews: 100 / total: 9461
[97/100] Beach Buggy Racing (com.vectorunit.purple.googleplay) - reviews: 100 / total: 9561
[98/100] Cell: Idle Factory Incremental (com.OctocubeGamesCompany.CIFI) - reviews: 0 / total: 9561
[99/100] Idle Miner Tycoon: Gold Games (com.fluffyfairygames.idleminertycoon) - reviews: 100 / total: 9661
[100/100] Hotel Empire Tycoon－Idle Game (com.codigames.hotel.empire.tycoon.idle.game) - reviews: 100 / total: 9761

,app_id,title,review_id,review_text,review_score,review_date,thumbs_up_count,review_created_version
0,com.king.candycrushsaga,Candy Crush Saga,d07f84ae-3b1a-44bd-9c96-3c4895446156,I love a dopamine rush!,5,2026-06-07 18:06:18,0,1.329.0.1
1,com.king.candycrushsaga,Candy Crush Saga,515baacd-052f-455b-becf-f76da3522158,Unable to play after the new update.. Kindly f...,3,2026-06-07 18:05:58,0,1.329.0.1
2,com.king.candycrushsaga,Candy Crush Saga,359257e8-75f8-4728-9fad-84cf5509f135,Nice well game 👍,5,2026-06-07 18:05:29,0,NaN
3,com.king.candycrushsaga,Candy Crush Saga,05f385eb-d5bf-46c9-a9ad-cf853fa463b2,very interesting this game,4,2026-06-07 17:55:20,0,1.326.0.1
4,com.king.candycrushsaga,Candy Crush Saga,7b7804d9-6300-448f-ac34-2b29aa0f3642,nice game,5,2026-06-07 17:45:33,0,1.328.0.1

Review shape: (9761, 8)
Unique apps in reviews: 99
Saved: C:\취준\mobile-game-retention-review-ua-analysis\data\collected\google_play_reviews.csv

In [9]:
# 8. 수집 결과 품질 점검
collection_summary = {
    "target_app_count": TARGET_APP_COUNT,
    "collected_app_id_count": len(app_ids),
    "valid_app_count": len(valid_app_ids),
    "review_row_count": len(reviews_df),
    "review_app_count": reviews_df["app_id"].nunique() if len(reviews_df) > 0 else 0,
    "missing_review_text_count": reviews_df["review_text"].isna().sum() if len(reviews_df) > 0 else None,
    "missing_review_score_count": reviews_df["review_score"].isna().sum() if len(reviews_df) > 0 else None,
}

collection_summary_df = pd.DataFrame([collection_summary])
display(collection_summary_df)

collection_summary_df.to_csv(
    OUTPUT_TABLE_DIR / "google_play_collection_summary.csv",
    index=False,
    encoding="utf-8-sig",
)

# 앱별 리뷰 수
if len(reviews_df) > 0:
    app_review_count = (
        reviews_df.groupby(["app_id", "title"])
        .agg(
            review_count=("review_id", "count"),
            avg_review_score=("review_score", "mean"),
        )
        .reset_index()
        .sort_values("review_count", ascending=False)
    )

    display(app_review_count.head(20))

    app_review_count.to_csv(
        OUTPUT_TABLE_DIR / "google_play_app_review_count.csv",
        index=False,
        encoding="utf-8-sig",
    )

,target_app_count,collected_app_id_count,valid_app_count,review_row_count,review_app_count,missing_review_text_count,missing_review_score_count
0,100,100,100,9761,99,0,0

,app_id,title,review_count,avg_review_score
0,bubbleshooter.orig,Bubble Shooter - Classic Pop,100,4.24
1,com.JindoBlu.Antistress,Antistress - relaxation toys,100,4.74
2,com.JindoBlu.OfflineGames,Offline Games - No Wifi Games,100,4.58
3,com.Seriously.BestFiends,Best Fiends - Match 3 Puzzles,100,3.97
4,com.WalkTalk.FlightMaster,Epic Plane Evolution,100,3.52
5,com.bandagames.mpuzzle.gp,Magic Jigsaw Puzzles－Games HD,100,4.81
6,com.block.juggle,Block Blast!,100,4.64
7,com.codigames.hotel.empire.tycoon.idle.game,Hotel Empire Tycoon－Idle Game,100,4.00
8,com.crazylabs.lady.bug,Miraculous Ladybug & Cat Noir,100,4.16
9,com.creations.runnergame,Kooply Run™: Play and Create!,100,3.83
10,com.devsisters.cos,CookieRun: OvenSmash,100,3.47
11,com.dreamgames.royalkingdom,Royal Kingdom,100,4.04
12,com.dreamgames.royalmatch,Royal Match,100,4.51
13,com.ea.game.nfs14_row,Need for Speed™ No Limits,100,4.17
14,com.ea.game.pvzfree_row,Plants vs. Zombies™,100,3.35
15,com.easybrain.art.puzzle,Art Puzzle - Puzzle Games,100,4.27
16,com.easybrain.block.puzzle.games,Blockudoku®: Block Puzzle Game,100,3.70
17,com.easybrain.jigsaw.puzzles,Jigsaw Puzzles - Puzzle Games,100,4.00
18,com.easybrain.sudoku.android,Sudoku.com - Classic Sudoku,100,3.74
19,com.ecffri.arrows,Arrows – Puzzle Escape,100,4.72

In [10]:
# 9. 리뷰 데이터 간단 전처리
if len(reviews_df) > 0:
    reviews_cleaned = reviews_df.copy()

    reviews_cleaned["review_text"] = reviews_cleaned["review_text"].fillna("").astype(str)
    reviews_cleaned["review_text_lower"] = reviews_cleaned["review_text"].str.lower()
    reviews_cleaned["review_date"] = pd.to_datetime(reviews_cleaned["review_date"], errors="coerce")
    reviews_cleaned["review_score"] = pd.to_numeric(reviews_cleaned["review_score"], errors="coerce")

    # 중복 제거
    before = len(reviews_cleaned)
    reviews_cleaned = reviews_cleaned.drop_duplicates(subset=["review_id"])
    after = len(reviews_cleaned)

    print("Before duplicates removed:", before)
    print("After duplicates removed:", after)
    print("Removed:", before - after)

    reviews_cleaned.to_csv(
        PROCESSED_DIR / "google_play_reviews_cleaned.csv",
        index=False,
        encoding="utf-8-sig",
    )

    display(reviews_cleaned.head())

else:
    print("No reviews collected.")

Before duplicates removed: 9761
After duplicates removed: 9761
Removed: 0

,app_id,title,review_id,review_text,review_score,review_date,thumbs_up_count,review_created_version,review_text_lower
0,com.king.candycrushsaga,Candy Crush Saga,d07f84ae-3b1a-44bd-9c96-3c4895446156,I love a dopamine rush!,5,2026-06-07 18:06:18,0,1.329.0.1,i love a dopamine rush!
1,com.king.candycrushsaga,Candy Crush Saga,515baacd-052f-455b-becf-f76da3522158,Unable to play after the new update.. Kindly f...,3,2026-06-07 18:05:58,0,1.329.0.1,unable to play after the new update.. kindly f...
2,com.king.candycrushsaga,Candy Crush Saga,359257e8-75f8-4728-9fad-84cf5509f135,Nice well game 👍,5,2026-06-07 18:05:29,0,NaN,nice well game 👍
3,com.king.candycrushsaga,Candy Crush Saga,05f385eb-d5bf-46c9-a9ad-cf853fa463b2,very interesting this game,4,2026-06-07 17:55:20,0,1.326.0.1,very interesting this game
4,com.king.candycrushsaga,Candy Crush Saga,7b7804d9-6300-448f-ac34-2b29aa0f3642,nice game,5,2026-06-07 17:45:33,0,1.328.0.1,nice game

In [11]:
# 10. 앱 메타데이터 간단 전처리
apps_cleaned = valid_apps_df.copy()

# 날짜 변환
apps_cleaned["updated"] = pd.to_datetime(apps_cleaned["updated"], unit="ms", errors="coerce")

# 숫자형 변환
numeric_cols = ["score", "ratings_count", "reviews_count", "min_installs", "real_installs", "price"]
for col in numeric_cols:
    if col in apps_cleaned.columns:
        apps_cleaned[col] = pd.to_numeric(apps_cleaned[col], errors="coerce")

# boolean 정리
bool_cols = ["free", "contains_ads", "in_app_purchase"]
for col in bool_cols:
    if col in apps_cleaned.columns:
        apps_cleaned[col] = apps_cleaned[col].astype("boolean")

apps_cleaned.to_csv(
    PROCESSED_DIR / "google_play_apps_cleaned.csv",
    index=False,
    encoding="utf-8-sig",
)

display(apps_cleaned.head())
print("Apps cleaned shape:", apps_cleaned.shape)

,app_id,title,developer,genre,genre_id,score,ratings_count,reviews_count,installs,min_installs,real_installs,free,price,currency,contains_ads,in_app_purchase,updated,released,content_rating,url
0,com.king.candycrushsaga,Candy Crush Saga,King,Casual,GAME_CASUAL,4.626835,38939374.0,2094860.0,"1,000,000,000+",1000000000,2261402010,True,0.0,USD,True,True,1970-01-21 14:26:03.225,"Nov 15, 2012",Everyone,https://play.google.com/store/apps/details?id=...
1,com.moonactive.coinmaster,Coin Master,Moon Active,Casual,GAME_CASUAL,4.751316,10382177.0,691073.0,"100,000,000+",100000000,345137646,True,0.0,USD,True,True,1970-01-21 14:31:37.778,"Feb 4, 2016",Teen,https://play.google.com/store/apps/details?id=...
2,com.JindoBlu.OfflineGames,Offline Games - No Wifi Games,JindoBlu,Casual,GAME_CASUAL,4.640068,457166.0,13820.0,"100,000,000+",100000000,192362829,True,0.0,USD,True,True,1970-01-21 14:41:05.641,"Aug 4, 2023",Everyone,https://play.google.com/store/apps/details?id=...
3,com.king.candycrushsodasaga,Candy Crush Soda Saga,King,Casual,GAME_CASUAL,4.578125,8874939.0,390688.0,"500,000,000+",500000000,616471412,True,0.0,USD,True,True,1970-01-21 14:17:48.032,"Nov 11, 2014",Everyone,https://play.google.com/store/apps/details?id=...
4,com.block.juggle,Block Blast!,HungryStudio,Puzzle,GAME_PUZZLE,4.820772,4769045.0,70652.0,"500,000,000+",500000000,969039804,True,0.0,USD,True,True,1970-01-21 14:37:41.750,"Sep 23, 2022",Everyone,https://play.google.com/store/apps/details?id=...

Apps cleaned shape: (100, 20)

In [12]:
# 11. 데이터 수집 문서 저장
collection_doc = f"""
# Google Play 게임 앱/리뷰 데이터 수집 요약

## 수집 목적
모바일 게임 앱마켓에서 관찰 가능한 유저 경험 신호를 분석하기 위해 Google Play의 게임 앱 메타데이터와 최신 리뷰를 수집했다.

## 수집 기준
- 국가: {COUNTRY}
- 언어: {LANG}
- 목표 앱 수: {TARGET_APP_COUNT}
- 앱별 목표 리뷰 수: {REVIEWS_PER_APP}

## 수집 결과
- 수집 앱 ID 수: {len(app_ids)}
- 유효 앱 수: {len(valid_app_ids)}
- 수집 리뷰 수: {len(reviews_df)}
- 리뷰가 수집된 앱 수: {reviews_df["app_id"].nunique() if len(reviews_df) > 0 else 0}

## 수집 컬럼

### 앱 메타데이터
- app_id
- title
- developer
- genre
- score
- ratings_count
- reviews_count
- installs
- free
- contains_ads
- in_app_purchase
- updated
- content_rating

### 리뷰 데이터
- app_id
- title
- review_id
- review_text
- review_score
- review_date
- thumbs_up_count
- review_created_version

## 해석 범위
이 데이터는 앱마켓에서 관찰 가능한 리뷰와 메타데이터 기반 유저 경험 신호를 분석하기 위한 데이터다.
개별 리뷰를 특정 UA 캠페인, 광고 채널, 유저 획득 비용과 직접 연결하지 않는다.
캠페인 KPI/ROAS 분석과는 독립 파트로 해석하며, 최종 종합 인사이트에서만 논리적으로 연결한다.
"""

doc_path = DOCS_DIR / "data_collection_plan.md"
doc_path.write_text(collection_doc, encoding="utf-8")

print("Saved:", doc_path)

Saved: C:\취준\mobile-game-retention-review-ua-analysis\docs\data_collection_plan.md